In [14]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])#You are now converting a list into a numpy array
b = np.array([5, 4, 3, 2, 1])#An array needs everything in the same value, so if there is a string, all are strings

print a
print b

[1 2 3 4 5]
[5 4 3 2 1]


In [18]:
print(a + b)
print np.add(a,b)
print np.subtract(a,b)

[6 6 6 6 6]
[6 6 6 6 6]
[-4 -2  0  2  4]


In [19]:
aPrime = np.array([1, 2, 3, 4, 5, 6])
print np.add(aPrime,b)#This runs an error because you can't add arrays of different value amounts

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [23]:
np.dot(a,b)#This will multiply each pair of values in your arrays, and then sum the results of each
np.dot(a,b)

35

In [ ]:
x = np.array([7, 11, 14, 19, 21])
y = np.array([12, 19, -3, 4, -16])

